#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure Step
#

require "autorake/mkconfig"

Autorake.configure {

  extending_ruby

  if RUBY_VERSION < "1.9.2" then
    enable :array_select_bang
    if RUBY_VERSION < "1.9" then
      enable :string_ord
      enable :string_clear
      if RUBY_VERSION < "1.8.7" then
        enable :array_index_with_block
        enable :kernel_tap
        enable :string_start_with
        enable :thread_exclusive
      end
      have_header "rubysig.h"
    end
  end

  if RUBY_VERSION < "1.9" then
    have_header "ruby.h"
    have_header "st.h"
    have_header "rubyio.h"
    have_header "re.h"
  else
    have_header "ruby/ruby.h"
    have_header "ruby/st.h"
    have_header "ruby/io.h"
    have_header "ruby/re.h"
  end

}

