#!/usr/bin/env ruby

#
#  mkrf_conf  --  configure Supplement
#

require "autorake/mkconfig"

Autorake.configure {

  extending_ruby

  if RUBY_VERSION < "3.3" then
    if RUBY_VERSION < "2.7" then
      if RUBY_VERSION < "2.6" then
        enable :dir_children
      end
    else
      enable :super_kwargs
    end
    enable :old_io_functions
  end

  have_header "ruby/ruby.h"
  have_header "ruby/st.h"
  have_header "ruby/io.h"
  have_header "ruby/re.h"

  have_function "rb_thread_wait_for"

  have_function "cbrt"

}

