#
#  Rakefile  --  build some libraries
#


require "rake/autorake"

extend Rake::Configure


rule ".o" => ".c" do |t|
  cc t.name, t.source, "-O2", "-fPIC"
end


DLs = {
  "step.so"          => %w(step.o sync.o),
  "step/filesys.so"  => %w(step/filesys.o),
  "step/itimer.so"   => %w(step/itimer.o),
  "step/terminal.so" => %w(step/terminal.o),
}

DLs.each { |k,v|
  task k => v do |t|
    ld t.name, t.prerequisites, "-shared"
  end
}


task :default => DLs.keys


task :clean do
  FileList[ "**/*.o", "**/*.so"].each { |f| rm_f f }
end

