#
#  Rakefile  --  build some libraries
#

require "autorake"

c = compiler "-O2", "-fPIC"
l = linker "-shared"

rule ".o" => ".c" do |t|
  c.cc t.name, t.source
end

DLs = {
  "step.so"          => %w(step.o sync.o),
  "step/filesys.so"  => %w(step/filesys.o),
  "step/itimer.so"   => %w(step/itimer.o),
  "step/terminal.so" => %w(step/terminal.o),
}

DLs.each { |k,v|
  task k => v do |t|
    l.cc t.name, t.prerequisites
  end
}

task :default => DLs.keys

task :clean do
  FileList[ "**/*.o", "**/*.so"].each { |f| rm_f f }
end

