#
#  Rakefile  --  build some libraries
#

require "autorake"

c = compiler "-O2", "-fPIC"
l = linker "-shared"

rule ".o" => ".c" do |t|
  c.cc t.name, t.source
end

DLs = {
  "supplement.so"          => %w(supplement.o process.o),
  "supplement/locked.so"   => %w(supplement/locked.o),
  "supplement/filesys.so"  => %w(supplement/filesys.o),
  "supplement/itimer.so"   => %w(supplement/itimer.o),
  "supplement/terminal.so" => %w(supplement/terminal.o),
}

DLs.each { |k,v|
  task k => v do |t|
    l.cc t.name, t.prerequisites
  end
}

task :default => DLs.keys

task :clean do
  FileList[ "**/*.o", "**/*.so"].each { |f| rm_f f }
end

